[package]
name = "my-engine"
version = "0.1.0"
authors = ["LukeB"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


ggez = "*"
rand = "0.7.3"
byteorder = "1.2.7"